name: Build PyCryptodome for iOS arm64

on:
  workflow_dispatch:

jobs:
  build-wheel:
    runs-on: macos-latest
    env:
      CIBW_ARCHS_MACOS: "arm64"
      CIBW_BUILD: "cp310-*"
      CIBW_SKIP: "pp*"
      CIBW_COMPILER: "clang"
    steps:
      - name: Check out source
        uses: actions/checkout@v4

      - name: Extract source tarball
        run: |
          tar xzf pycryptodome-3.22.0.tar.gz

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel cibuildwheel

      - name: Build wheels
        run: |
          cibuildwheel pycryptodome-3.22.0 --output-dir wheelhouse

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pycryptodome-cp310-macosx_arm64
          path: wheelhouse/*.whl
